[package]
name = "day19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
counter = "0.5.2"
itertools = "0.10.3"
nalgebra = "0.29.0"
serde_scan = "0.4.1"
